% Find average .fig files from R and L eye and combine into single figure
% IMPORTANT - Assumes all average fig files are paired (no R plot without an L plot and vice versa)
% Requires getAllFiles_F function (from ERG data from JSON project functions folder)
% david.alston@louisville.edu (6-28-2024)
% NOTE - Use with old (pre 7-2-2025) figures which use R and L in figure title/filename
clc
close all
clear
addpath(genpath('Functions'));
%% CONTROLS
rColor = 'r'; % Changes all text/line colors to be this color
lColor = 'k';
%% Select input path with figures and grab all figures
figPath = uigetdir();
if figPath == 0; return; end % User cancelled prompt
allFigs = getAllFiles_F(figPath, {'.fig'}); % All figures (avg and individual)
%% Filter down to just average figs
% Loop is slow here, but not that many figs so
remVec = false(size(allFigs));
for fN = 1:numel(allFigs)
    currStart = allFigs(fN).name(1:4); % All avg figs filename starts with 'AVG-'
    if ~strcmp(currStart, 'AVG-') % Case sensitive string compare
        remVec(fN) = true;
    end
end
avgFigs = allFigs;
avgFigs(remVec) = [];
%% Skip any existing replotted average figures (generated by this script)
existingCombVec = false(size(avgFigs));
for fN = 1:numel(avgFigs)
    if contains(avgFigs(fN).name, '-RvsL-', 'IgnoreCase', false)
        existingCombVec(fN) = true;
    end
end
avgFigs = avgFigs(~existingCombVec);
%% Get R vs L figs
isRVec = false(size(avgFigs));
for fN = 1:numel(avgFigs)
    if contains(avgFigs(fN).name, '-R-', 'IgnoreCase', false)
        isRVec(fN) = true;
    end
end
R_AvgFigs = avgFigs(isRVec);
L_AvgFigs = avgFigs(~isRVec);
%% Because of default matlab sorting, R_ and L_ figs in order already. Replot and save
if numel(R_AvgFigs) ~= numel(L_AvgFigs)
    beep;
    disp('ERROR:: Odd number of total average figures. At least one average is missing its plot for the opposite eye. Use ODOSTitle script? Closing...');
    return
end
for fN = 1:numel(R_AvgFigs)
    fprintf('Generating figure %i of %i\n', fN, numel(R_AvgFigs));
    rFigFull = fullfile(R_AvgFigs(fN).folder, R_AvgFigs(fN).name);
    lFigFull = fullfile(L_AvgFigs(fN).folder, L_AvgFigs(fN).name);
    rFig = openfig(rFigFull, "new", "invisible");
    lFig = openfig(lFigFull, "new", "visible");
    % ^ Can edit as invisible, but when saved it also saves as invisible
    % (can't just double click open with Matlab)
    %{
        10 data entries, 4 text and 6 lines
        
        from rFig.Children.Children.Children(N):
        
        N
        1 = Text = TTP
        2 = Text = b-wave
        3 = Text = TTT
        4 = Text = a-wave
        
        Now line plots:
        
        5 = Zero dashed black line
        6 = Peak dashed red line
        7 = Trough dashed red line
        8 = SEM bottom
        9 = SEM top
        10 = Main average line
    %}
    %% Set line/txt color
    for rFigN = 1:numel(rFig.Children.Children.Children)
        if ~strcmp(rFig.Children.Children.Children(rFigN).Type, 'constantline')
            rFig.Children.Children.Children(rFigN).Color = rColor;
        end
    end
    for lFigN = 1:numel(lFig.Children.Children.Children)
        if ~strcmp(lFig.Children.Children.Children(lFigN).Type, 'constantline')
            lFig.Children.Children.Children(lFigN).Color = lColor;
        end
    end
    %% Shift the four text boxes Y position from the right eye so are visible
    yShift = 0.1; % Normalized units (0 to 1)
    % rFig.Children.Children.Children returns the 10 graphics objects in
    % the layout (numel(this) is 10):
    %{
        1 = constantline
        2-5 = text (4 total)
        
    %}
    for gObj = 1:numel(rFig.Children.Children.Children)
        if strcmp(rFig.Children.Children.Children(gObj).Type, 'text')
           rFig.Children.Children.Children(gObj).Position(2) = rFig.Children.Children.Children(gObj).Position(2) - yShift;% Position as [X Y 0] 
        end
    end
    %% Copy line objects onto left figure
    rObjLines = findobj(rFig, 'type', 'line'); % Only copy the lines over
    copyobj(rObjLines, findobj(lFig, 'type', 'axes'));
    %% Copy text objects onto left figure
    rObjTxt = findobj(rFig, 'type', 'text'); % Only copy the text over
    copyobj(rObjTxt, findobj(lFig, 'type', 'axes'));
    %% Alter figure title so shows that it is R vs L
    currTitle = lFig.Children.Children.Title.String; % Need to remove '-L-'
    lFig.Children.Children.Title.String = strrep(currTitle, '-L-', '-R vs L-');
    %% Add legend, but only for main line plot
    mainIDsC = 0;
    for combObjN = 1:numel(lFig.Children.Children.Children)
        if strcmp(lFig.Children.Children.Children(combObjN).Type, 'line') % The 8 lines plotted
            if strcmp(lFig.Children.Children.Children(combObjN).LineStyle, '-') % one of the two main dashed lines
                mainIDsC = mainIDsC + 1;
                mainIDs(mainIDsC) = combObjN; %#ok<SAGROW>
            end
        end
    end
    if numel(mainIDs) ~= 2
        beep;
        fprintf("ERROR:: Could not find both main lines to add to figure. Contact David Alston if this error occurs. Skipping to next figure...\n");
        continue;
    end
    legend([lFig.Children.Children.Children(mainIDs(1)), lFig.Children.Children.Children(mainIDs(2))], {'R', 'L'});
    %% Save new combined figure to file
    rFigName = strrep(R_AvgFigs(fN).name, '-R-', '-RvsL-');
    fullOut = fullfile(R_AvgFigs(fN).folder, rFigName);
    lFig.WindowState = 'maximized';
    saveas(lFig, fullOut);
    close all
end